document:
  dsl: 1.0.0
  taskQueue: order-processing
  workflowType: orderProcessing
  version: 0.1.0
do:
  - orderProcessing:
      do:
        - validateOrder:
            set:
              validated: true
        - waitForPayment:
            wait:
              seconds: 30
        - fulfilOrder:
            call: http
            with:
              method: POST
              endpoint:
                uri: https://example.com/orders/fulfil
